/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from '@react-three/drei'
import type { ObjectMap } from '@react-three/fiber'
import { type JSX } from 'react'
import type { Mesh, MeshStandardMaterial } from 'three'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF &
  ObjectMap & {
    nodes: {
      Cube007_Cube008: Mesh
      Cube006_Cube007: Mesh
      Cylinder013: Mesh
      Cylinder012: Mesh
      Cylinder011: Mesh
      Cylinder010: Mesh
      Cylinder009: Mesh
      Cube005_Cube006: Mesh
      Cylinder008: Mesh
      Cylinder007: Mesh
      Cube004_Cube005: Mesh
      Cylinder006: Mesh
      Cylinder005: Mesh
      Cube003_Cube004: Mesh
      Cube002_Cube003: Mesh
      Cube001_Cube002: Mesh
      Plane001_Plane002: Mesh
      Cylinder004: Mesh
      Cylinder003: Mesh
      Cylinder002: Mesh
      Cylinder001: Mesh
      Cylinder: Mesh
      Cube_Cube001: Mesh
    }
    materials: {
      GrayPlastic: MeshStandardMaterial
      BlackCoatSteel: MeshStandardMaterial
      WhiteSteelScrew: MeshStandardMaterial
      BlackPlastic: MeshStandardMaterial
      BlackWood: MeshStandardMaterial
    }
  }

export function Desk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/desk.glb') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007_Cube008.geometry}
        material={materials.GrayPlastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006_Cube007.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.WhiteSteelScrew}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.BlackPlastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_Cube006.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.BlackPlastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.WhiteSteelScrew}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004_Cube005.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials.WhiteSteelScrew}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.BlackPlastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003_Cube004.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002_Cube003.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001_Cube002.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001_Plane002.geometry}
        material={materials.BlackWood}
        material-color="#C4A484"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.BlackPlastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.WhiteSteelScrew}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.BlackCoatSteel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Cube001.geometry}
        material={materials.BlackCoatSteel}
      />
    </group>
  )
}

useGLTF.preload('/models/desk.glb')
